Gerenciador:
    TelaInicial:
    TelaNexus:

<TelaInicial>:
    name: "inicial"
    BoxLayout:
        orientation: "vertical"
        padding: 20
        spacing: 20
        Label:
            text: "STELA NEXUS"
            font_size: 32
            bold: True
        Button:
            text: "Entrar no Nexus"
            font_size: 22
            size_hint_y: None
            height: 60
            on_release: app.root.current = "nexus"

<TelaNexus>:
    name: "nexus"
    BoxLayout:
        orientation: "vertical"
        padding: 20
        Label:
            text: "Nexus Ativo - Stela online"
        Button:
            text: "Voltar"
            size_hint_y: None
            height: 50
            on_release: app.root.current = "inicial"
