name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: |
          pip install buildozer cython
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk libncurses5
          buildozer android debug
      - uses: actions/upload-artifact@v3
        with:
          name: apk
          path: bin/*.apk
